# -*- coding: utf-8 -*-
"""Mikroprocesory3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j7oa2III9wIWSVY7P-9n3-azJ7k04Cej
"""

def my_function():
  print("My useful function")
  
  
def my_average(list_of_numbers):
  average = sum(list_of_numbers)/(len(list_of_numbers))
  

  my_int = 10
  my_list = [0,1,2]
  my_function()
  computed_avg = my_average(my_list)
  print(computed_avg)
  print("test")