# -*- coding: utf-8 -*-
"""Python_trenink.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1exC2fGY-w7_w3jYz5TlUtpLI55Wo5dt-
"""

if 5>2:
  print("true")

x = 5
y = "Libor"

print(y)
a = " awesome"
print("python is" + a)
def f1():
  x = 10
  print(10+x)
 
f1()

def f2():
  global X
  X = "mamka"

print(f2())
g = int(2.8) # int. zaokrouhluje dolů na celé číslo

g
81%4 # % dává zbytek po dělení

b = "tata"
print(b[2]) # vytiskne písmeno na pozici
print(a[2:5]) # vytiskne určitou délku slova
print(len(a)) # vytiskne délku slova
print(a.replace("a","w"))

c ="awe" not in a # ověří výskyt části textu v proměnné
print(c)

age = 23
text = "Hi, I'm John and my age is {}"
print(text.format(age))

list = ["nazgul","saruman","sauron","frodo","gandalf","gimli","aragorn","legolas"]

print(list[2])
print(list[-1])

for x in list:
  print(x) #vytisknutí celého "list"

if "gimli" in list:
  print("gimli is da best")
  
list.append("boromir") # přidání výrazu do "list" (.remove pro odebrání)

print (list)



