# -*- coding: utf-8 -*-
"""Python2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbzJYd9MsdMyWBZHvakESJkZgRzkw8yH
"""

if (3>4):
  print("true")
else:
  print("false")

1<2
1<2 or 4<3



if (a>4):
  print("b=2")
else:
  print("b=5")

  if(a>5):
    c=4
  else:
    c=6
c

x=0
while(x<10):
  print(x)
  x +=1
  if x==5:
    print("end")
  break

  
  
z=0
while(z<101):
  z+=1
  if (z%3==0):
    print("Fizz")
  elif (z%5==0):
    print("Buzz")
  else:
    print(z)
    
    
table= "abcdefghijklmnopqrstuvwxyz "
text="ahoj"
print(a)

table="abcdefghijklmnopqrstuvwxyz "
text="ahoj"
key = 10

for letter in text:
  print(table[table.index(letter)+key])

a=112
b=248

D=100
while(D>0):
  D-=1
  if(a%D==0):
    if(b%D==0):
      print(D)
      break