# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19WhoX9fXzThek-1ujZOrdwmGGKoxwcmF
"""

import numpy as np
numpy_matrix = np.zeros((3,3))
numpy_matrix[1,2] = 7

my_numpy_array = np.array([1, 2, 3, 4])
print(numpy_matrix)
print(np.sin(my_numpy_array))