# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k8ecy6jtiT7za5h1KXsPW_BjMo4wNplM
"""

# norma PEP8
print("Hello World!")
variable = 10.
print(variable)
print(type(variable))

my_list = [10, "my_string", [1, 2, 3]]
print(my_list)
my_list.append("next_item")
print(my_list[2])

my_dictionary = {"keyword1" : 10, "keyword2" : 50}
print(my_dictionary)
print(list(my_dictionary))

my_set = set([1,2,3])
print(my_set)

my_tuple = (1, 2, 3)
print(my_tuple[0])

print(2+4)
print(81%12)
print ("my_string" + "another_string")
print(len(my_list))
print(3//2)

print(5 * "ahoj\n")
print(False + 1)
print(False + 2)

print(dir(my_list))
print("Hello, World, Dog".split(" "))

