# -*- coding: utf-8 -*-
"""vizualizace dat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnbhBkBZjyEAAf0BCcdkRrdmYDQGzc9_
"""

import matplotlib.pyplot as plt


my_list = [0, 1, 4, 9, 16, 25, 36]

plt.plot(my_list)
#plt.ylabel("Y")
#plt.xlabel("X")
#plt.title("Druhamocnina")


plt.figure("Histogram")
plt.hist(my_list)
plt.show()